CREATE TABLE professionals (
                               id UUID NOT NULL PRIMARY KEY,
                               name VARCHAR(255) NOT NULL
);

CREATE TABLE professional_services (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                                       name VARCHAR(255) NOT NULL,
                                       price DOUBLE PRECISION,
                                       professional_id UUID,
                                       CONSTRAINT fk_service_professional FOREIGN KEY (professional_id) REFERENCES professionals(id)
);

CREATE TABLE professionals_services (
                                        professional_id UUID NOT NULL,
                                        services_id BIGINT NOT NULL,
                                        CONSTRAINT fk_rel_professional FOREIGN KEY (professional_id) REFERENCES professionals(id),
                                        CONSTRAINT fk_rel_service FOREIGN KEY (services_id) REFERENCES professional_services(id)
);