CREATE TABLE appointment_item (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                                  schedule_id UUID,
                                  professional_services_id BIGINT,
                                  applied_price DOUBLE PRECISION,
                                  CONSTRAINT fk_item_schedule FOREIGN KEY (schedule_id) REFERENCES schedules(id),
                                  CONSTRAINT fk_item_service FOREIGN KEY (professional_services_id) REFERENCES professional_services(id)
);